// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SenderAddress struct {
	_tab flatbuffers.Table
}

func GetRootAsSenderAddress(buf []byte, offset flatbuffers.UOffsetT) *SenderAddress {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SenderAddress{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *SenderAddress) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SenderAddress) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SenderAddress) Host() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *SenderAddress) Port() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SenderAddress) MutatePort(n uint16) bool {
	return rcv._tab.MutateUint16Slot(6, n)
}

func SenderAddressStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func SenderAddressAddHost(builder *flatbuffers.Builder, Host flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(Host), 0)
}
func SenderAddressAddPort(builder *flatbuffers.Builder, Port uint16) {
	builder.PrependUint16Slot(1, Port, 0)
}
func SenderAddressEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
